package com.dadiyang.wx.entity;

public class SystemUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.id
     *
     * @mbg.generated Thu Jun 28 14:13:28 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.id
     *
     * @return the value of system_user.id
     *
     * @mbg.generated Thu Jun 28 14:13:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.id
     *
     * @param id the value for system_user.id
     *
     * @mbg.generated Thu Jun 28 14:13:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}